services:

  n8n:
    build: .
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${DOMAIN_NAME-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL-http}
      - NODE_ENV=development
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=${WEBHOOK_URL-http://localhost:5678/}
      - GENERIC_TIMEZONE=Europe/Budapest
      - N8N_LOG_LEVEL=debug
      - N8N_DIAGNOSTICS_ENABLED=true
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    volumes:
      - n8n_data:/home/node/.n8n
      - ./dist:/home/node/.n8n/custom/n8n-nodes-imagerouter

volumes:
  n8n_data:
